// ==========================================================
// 6.14.2 Завантаження даних у клієнтському компоненті
// підключення провайдера React Query
// ==========================================================
// 3) дані з components/TanStackProvider/TanStackProvider.tsx
// ----------------------------------------------------------
// 4) Провайдер підключається один раз на весь проєкт, тому зробимо це в головному шаблоні app/layout.tsx який огортає всі компоненти додатка.
// ==========================================================
//
// app/layout.tsx

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";

import TanStackProvider from "@/components/TanStackProvider/TanStackProvider";

// Підключення шрифтів
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TanStackProvider>
          <Header />
          <main>{children}</main>
          <footer>
            <p>
              Created <time dateTime="2025">2025</time>
            </p>
          </footer>
        </TanStackProvider>
      </body>
    </html>
  );
}
// ======================================================
// 6.7. Створення компонента - app/layout.tsx
// (Компонент RootLayout)
// ======================================================
//
// import type { Metadata } from "next";
//
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Header from "@/components/Header/Header";

// // Підключення шрифтів
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         <Header />
//         <main>{children}</main>
//         <footer>
//           <p>
//             Created <time dateTime="2025">2025</time>
//           </p>
//         </footer>
//       </body>
//     </html>
//   );
// }

// ==============================================================
// ПОЧАТКОВИЙ КОД
// ==============================================================
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// Підключення шрифтів
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// // SEO - метадані (потрапляють у <head> сторінки);
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// // Компонент RootLayout (У body передається змінна зі шрифтами, children – це контент сторінок, які будуть відображатися всередині лейаут)

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         <header>
//           <h1>Hello Note Hub</h1>
//         </header>

//         <main>{children}</main>

//         <footer>
//           <p>
//             Created <time dateTime="2025">2025</time>
//           </p>
//         </footer>
//       </body>
//     </html>
//   );
// }

// ------------------------------
// Файл layout.tsx дозволяє задати спільну структуру для всіх сторінок. Це зручно, якщо потрібно відображати спільні елементи, як-от хедер, футер або бокове меню – без дублювання коду.

// ------------------------------
// Для чого потрібен Layout
// ------------------------------
// Визначає глобальний інтерфейс сторінки
// Відображається на всіх маршрутах, які лежать усередині app/
// Дозволяє обгорнути контент навколо children (тобто контенту сторінки)
// ------------------------------
// 1. Імпорти
// ------------------------------
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// ------------------------------
// Metadata – тип для опису SEO-даних сторінки
// Geist, Geist_Mono – Google-шрифти, підключені через next/font/google
// globals.css – глобальні стилі
// Ми до всього цього обовʼязково повернемось, але трохи згодом.

// ------------------------------
// 2. Підключення шрифтів
// ------------------------------
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
// ------------------------------
// Geist() і Geist_Mono() – підключають шрифти Geist (звичайний) і Geist Mono (моноширинний).
// variable: "--font-geist-sans" – створюють CSS-змінні для використання шрифтів у стилях.
// subsets: ["latin"] – завантажують лише латиницю, щоб зменшити вагу шрифтів.
// Ми до всього цього обовʼязково повернемось, але трохи згодом.

// ------------------------------
// 3. SEO-метадані
// ------------------------------
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// ------------------------------
// Дані, які потрапляють у <head> сторінки
// Ці метадані можна задавати глобально або окремо для кожної сторінки

// ------------------------------
// 4. Компонент RootLayout
// ------------------------------
// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// };
// ------------------------------
// Обгортає всі сторінки та компоненти
// У body передається змінна зі шрифтами
// children – це і є контент сторінок, які будуть відображатися всередині лейаута
